/** Declaration file generated by dts-gen
 *
 * 因为没有 d.ts 文件，所以在此处存一份代码，并自定义一个 d.ts 文件
 * https://github.com/filamentgroup/loadCSS/blob/master/src/loadCSS.js
 *
 */

export function loadCSS(href: any, before?: any, media?: any, attributes?: any): any;
