/** Declaration file generated by dts-gen
 *
 * https://github.com/filamentgroup/loadCSS/blob/master/src/loadCSS.js
 *
 */

export function loadCSS(href: any, before?: any, media?: any, attributes?: any): any;
